---
language: ruby
cache: bundler
sudo: false
rvm: 2.2.3
env:
  global:
  - GIT_COMMITTER_NAME: FOO
  - GIT_COMMITTER_EMAIL: FOO@example.com
  - GIT_AUTHOR_NAME: FOO
  - GIT_AUTHOR_EMAIL: FOO@example.com
  - GH_REPO: FOO/BAR
script:
  - git clone --quiet -b gh-pages https://github.com/$GH_REPO.git build && bundle exec middleman build
after_success:
  - cd build
  - git add -A
  - git status
  - git commit -m 'Updated by Travis CI'
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && git push --quiet https://$GH_TOKEN@github.com/$GH_REPO.git gh-pages -f 2> /dev/null'
branches:
  only:
    - master
